### ISSUE TITLE
STM32f103 virtual com connection win 10 problem

### ISSUE THREAD

**Issue by kb-embedded** [miniwinwm/BluePillDemo#1]
Hi,

Firstly thanks for the lots of good example project. I have a very important problem. I can't connect stm32f103 with pc via usb. When I connected blue pill and pc , pc didn't recognize device. I read couple article about this. I didn't find any driver work on win10. So Can you help me? How can I fix this connection problem.

**Comment by miniwinwm** [comment]
You need a ST Link programmer/debugger. They are cheap on ebay.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kb-embedded** [comment]
Thanks :)
