### ISSUE TITLE
debug/build error: .elf file does not exist

### ISSUE THREAD

**Issue by sophie-bernier** [miniwinwm/BluePillDemo#2]
Hi,

I am new to STM32CubeIDE and STM32 in general and Blue Pill in specifics. Your code is a godsend - if only I can get it to load! I am running STM32CubeIDE in Linux Mint 20.

I decided to start with the BluePillDemo_GPIO project and naively opened your project in the IDE by double-clicking on the .project file. The project popped up in my Project Explorer. So far so good. But when I hit the 'debug' button, I get this error:

![Screenshot from 2020-11-14 11-04-54](https://user-images.githubusercontent.com/29133957/99154008-b7ae3100-2669-11eb-9ded-0bbf769b97b8.png)

My CDT build console states:

```
11:04:27 **** Incremental Build of configuration Debug for project BluePillDemo_GPIO ****
make -j8 all 
arm-none-eabi-size   BluePillDemo_GPIO.elf 
   text	   data	    bss	    dec	    hex	filename
   4676	     20	   1572	   6268	   187c	BluePillDemo_GPIO.elf
Finished building: default.size.stdout
 

11:04:28 Build Finished. 0 errors, 0 warnings. (took 163ms)
```

If you can help me, I would very much appreciate it.
Sebastien B

**Comment by davidsi** [comment]
I'm having this same issue.  Did you find a solution?

**Comment by davidsi** [comment]
Found it!  The config file was obviously built on a windows machine... and the debug file has a "\" not a "/" in it.  Edit your config (main panel) and it works

**Comment by miniwinwm** [comment]
@davidsi Thanks for the update. The config file was built on a Windows machine and has not been tested on Linux.

**Comment by davidsi** [comment]
It has now 😎

David
