### ISSUE TITLE
BluePillDemo_Flash example, write val too large

### ISSUE THREAD

**Issue by jj-uk** [miniwinwm/BluePillDemo#3]
The data you're writing to flash is truncated.

https://github.com/miniwinwm/BluePillDemo/blob/master/BluePillDemo_Flash/Core/Src/main.c#L127

0xBADD10DE4 is not 32-bit.

**Comment by miniwinwm** [comment]
Thanks, that's a typo that I will fix.

**Comment by miniwinwm** [comment]
Fixed to remove typo
